### PR TITLE
♻️ Refactor `BlockLocator`

### LINKED ISSUE #2580: Remove `Func<BlockHash, long>` parameter from `BlockLocator()`
As there is no requirement for `indexBlockHash` and `indexByBlockHash`, although presumably these are supposed to be inverses of each other, this can actually affect and mess up the internal flow of logic. For instance

```csharp
Func<long, BlockHash?> indexToBlockHash = _ => new BlockHash();
Func<BlockHash, long> blockHashToIndex = _ => long.MaxValue;
BlockLocator locator = new BlockLocator(
    indexToBlockHash, blockHashToIndex, 10);
```

results in `OverflowException` due to creating an "infinite loop" (the loop is only broken by an unexpected error, not due to `break` condition being met).

### PR DESCRIPTION
**Pull request by greymistcube**
Closes #2580, #2581, #2582, and #2583.

The implementation is still subject to change depending on what constraints we decide to impose on `BlockChain<T>` instances and how we want to handle variety of cases arising from constraints, or lack there of. The issue is rather far reaching and not obvious to resolve. See #2585.

### CODE REVIEW

**Comment by greymistcube** [comment]
Few notes:
- Reverts most changes made in #2667 on `BlockLocator`
  - Decision to synchronize only `Tip.Index` and `Id` seem arbitrary.
  - Doing away with `_rwlock` on `IStore` access reliant upon "others will use it responsibly" is shaky.
  - If we don't want to care about `IStore` and want to explicitly synchronize only `Tip.Index` and `Id`, a separate lock should be used instead of using `_rwlock` as a proxy (which would require a lot more work).
  - I suspect the performance bottleneck was mostly from old `BlockHash` to `long` mapping which required to **load** `BlockDigest` each time. The problem with the parameter was already mentioned in #2580 and this is no longer true by getting rid of the access altogether.

File: Libplanet/Blockchain/BlockChain.cs [hunk 1]
```diff
@@ -1095,26 +1097,18 @@ public BlockChain<T> Fork(BlockHash point, bool inheritRenderers = true)
...
         {
-            Guid chainId;
-            BlockHash tipHash;
-
             _rwlock.EnterReadLock();
             try
             {
-                chainId = Id;
-                tipHash = Tip.Hash;
+                return BlockLocator.Create(
```
Comment (longfin) [inline Libplanet/Blockchain/BlockChain.cs:1103]: Well...  I'm still convinced that lock separation on here wasn't a trade-off between safety and performance, but was a sort of correction against unnecessary locking. (because we keep the immutability on previous blocks for a given chain id).

File: CHANGES.md [hunk 2]
```diff
@@ -55,6 +62,15 @@ To be released.
 
 ### Behavioral changes
 
+ -  Changed `BlockChain<T>.FindNextHashes()` to return at most `count`
+    number of `BlockHash`es regardless of the result.
+    `BlockChain<T>`. [[#2581], [#2584]]
```
Comment (longfin) [inline CHANGES.md:67]: Does it mean that `BlockChain<T>.FindNextHashes()` will return more hashes even after the branchpoint (to fit `count`)?

File: Libplanet/Blockchain/BlockLocator.cs [hunk 3]
```diff
@@ -1,80 +1,109 @@
...
             {
-                hashes.Add(hash);
-                long currentBlockIndex = indexByBlockHash(hash);
+                throw new ArgumentOutOfRangeException(
+                    $"Given {nameof(startIndex)} cannot be negative: {startIndex}");
+            }
+
+            BlockHash genesisHash = indexToBlockHash(0) ??
+                throw new ArgumentException(
+                    $"Given {nameof(indexToBlockHash)} should not be null at zero index.");
```
Comment (longfin) [inline Libplanet/Blockchain/BlockLocator.cs:90]:
```suggestion
                throw new ArgumentException(
                    $"Given {nameof(indexToBlockHash)} should not be null at zero index.",
                    nameof(indexToBlockHash));
```

File: Libplanet/Blockchain/BlockLocator.cs [hunk 4]
```diff
@@ -1,80 +1,109 @@
...
-            BlockHash? current = tipHash;
-            long step = 1;
-            var hashes = new List<BlockHash>();
-            while (current is { } hash)
+            if (startIndex < 0)
             {
-                hashes.Add(hash);
-                long currentBlockIndex = indexByBlockHash(hash);
+                throw new ArgumentOutOfRangeException(
+                    $"Given {nameof(startIndex)} cannot be negative: {startIndex}");
```
Comment (longfin) [inline Libplanet/Blockchain/BlockLocator.cs:85]:
```suggestion
                throw new ArgumentOutOfRangeException(
                    $"Given {nameof(startIndex)} cannot be negative: {startIndex}",
                    nameof(startIndex));
```

File: Libplanet/Blockchain/BlockLocator.cs [hunk 5]
```diff
@@ -1,80 +1,109 @@
...
         /// </summary>
         /// <param name="hashes">Enumerable of <see cref="BlockHash"/>es to convert from.</param>
+        /// <exception cref="ArgumentException">Thrown when <paramref name="hashes"/> is empty.
+        /// </exception>
         public BlockLocator(IEnumerable<BlockHash> hashes)
         {
-            _impl = hashes;
+            _impl = hashes.Any()
+                ? hashes.ToList()
+                : throw new ArgumentException($"Given {nameof(hashes)} cannot be empty.");
```
Comment (longfin) [inline Libplanet/Blockchain/BlockLocator.cs:26]:
```suggestion
                : throw new ArgumentException($"Given {nameof(hashes)} cannot be empty.", nameof(hashes));
```

it may exceed the line limit 😅

File: CHANGES.md [hunk 6]
```diff
@@ -8,8 +8,14 @@ To be released.
 
 ### Deprecated APIs
 
+ -  Removed `BlockLocator(Func<long, BlockHash?>, Func<BlockHash, long>, int)`
```
Comment (longfin) [inline CHANGES.md:11]: I think that we need to move this sentence to the Backward-incompatible API changes section.

**Review by longfin — COMMENTED** [review]
Apart from my hope(i.e., escaping from branch-point detection), it seems to help to clarify confusing points. 

Detailed questions and opinions are left as separate comments.

File: Libplanet/Blockchain/BlockChain.cs (hunk 1 above)
Comment (greymistcube) [reply Libplanet/Blockchain/BlockChain.cs:1103]: > because we keep the immutability on previous blocks for a given chain id

This is only implicitly guaranteed by our current practice/codebase. I do agree there is little to no danger in how we are currently using `IStore` and `BlockChain<T>`, but the `IStore` interface itself does not contractually guarantee such immutability (if we had something like `IWriteOnlyStore` with appropriate constraints, then I'd say we *really* don't need to worry about safety). The immutability assumption only comes from *knowing* the whole stack all the way up to `Swarm<T>` is not going to mess with "bad" `IStore` methods.

There is also the question of how we specify `BlockLocator`'s behavior. One of the following should apply:
- If `IStore` is assumed to be immutable on all previous `Block<T>`s for the current `BlockChain<T>.Tip` *and* `BlockChain<T>` (and in turn the `IStore`) is assumed to have *all* `Block<T>`s, then `BlockLocator` should not handle `null` for missing `Block<T>`s.
- If `IStore` is not assumed to be immutable or could be missing some `Block<T>`s, then `BlockLocator` should be designed to deal with missing `Block<T>`s.

The problem is, we have the latter as an implementation while assuming the former via usage (of `BlockChain<T>` and `IStore` *not* `BlockLocator`, which can be confusing). 🙄

Comment (longfin) [reply Libplanet/Blockchain/BlockChain.cs:1103]: - In the long term, I hope `BlockLocator` disappears and `BlockChain<T>` and `IStore` adjust together. but I don't think this is something that can be done right now.
- If the lock range can be reduced by tweaking `IStore`'s interface, I think it's worth considering for at least now.  
  - I'm not a fan of the Chain ID concept and think a universal storage interface is needed
  - but also I think it's expensive to pay for reducible locks until that happens.

File: Libplanet/Blockchain/BlockChain.cs [hunk 7]
```diff
@@ -964,35 +970,31 @@ public IImmutableSet<TxId> GetStagedTransactionIds()
...
-            if (branchpointIndex > 0)
+            if (!(Store.GetBlockIndex(branchpoint) is long branchpointIndex))
             {
-                count++;
+                return new Tuple<long?, IReadOnlyList<BlockHash>>(null, new BlockHash[0]);
             }
 
             var result = new List<BlockHash>();
-            foreach (BlockHash hash in Store.IterateIndexes(Id, branchpointIndex, count))
+            foreach (BlockHash hash in Store.IterateIndexes(Id, (int)branchpointIndex, count))
```
Comment (colibrishin) [inline Libplanet/Blockchain/BlockChain.cs:984]: It's a bit off-topic from this PR, but casting `long` block index into `int` seems odd.

Comment (greymistcube) [reply Libplanet/Blockchain/BlockChain.cs:984]: Eh, it is weird. We need to change `IStore` interface to accept `long` values at some point. 🙄

**Review by colibrishin — APPROVED** [review]

**Comment by greymistcube** [comment]
Welp, I don't see this getting merged anytime soon, so I'll scrap this. We still need to resolve issues #2580, #2581, #2582, and #2583 somehow. 🙄

**Comment by greymistcube** [comment]
On further inspection, we really need a better spec, and this has too many issues to discard really, affecting too many things up and down the stack (down to `IStore` and all the way up to `Swarm`). I see the lack of spec making the whole syncing process pretty much unworkable in its current form. 😑

I'll do away with `_lock`s for now, as it'd be safe. Changes of things breaking are fairly low, but I still think it'll be nearly undiscoverable implicit spec adding much maintenance overhead (i.e. not being sure whether a call to `BlockLocator()` constructor is safe or not) to whoever tries to work on syncing. 🙁
