### PR TITLE
`TxPolicyViolationException` should contain `InnerException`

### LINKED ISSUE #1830: `TxPolicyViolationException` should contain `InnerException`
`BlockChain<T>.Append()` method currently throws `TxPolicyViolationException` without filling its `InnerException` if a transaction is invalid according to the `BlockChain<T>.Policy`.  Although such behavior is not a bug, but it makes hard to investigate why it is invalid.

It would be better if it includes the original exception made by `IBlockPolicy<T>.ValidateNextBlockTx()` as its `InnerException`.  See also:

<https://github.com/planetarium/libplanet/blob/be4dd0195d48b7eb08d85735af660d20fc2ac01f/Libplanet/Blockchain/BlockChain.cs#L888-L893>

### PR DESCRIPTION
**Pull request by colibrishin**
This is squashed PR of #1912, and resolves #1830.

### CODE REVIEW

**Comment by riemannulus** [comment]
Need changelog fix 😢

**Comment by colibrishin** [comment]
Commits are squashed and changelog finally has been fixed. 😊

File: Libplanet/Tx/InvalidTxException.cs [hunk 1]
```diff
@@ -16,12 +16,32 @@ public abstract class InvalidTxException : Exception
...
 
+        /// <summary>
+        /// Instantiates a new exception object with proper metadata.
+        /// </summary>
+        /// <param name="txid">The invalid <see cref="Transaction{T}"/>'s
+        /// <see cref="Transaction{T}.Id"/>.  It is automatically included to
+        /// the <see cref="Exception.Message"/> string.</param>
+        /// <param name="message">A descriptive error message for programmers.
+        /// </param> <param name="innerException">The <see cref="Exception"/> for
+        /// <see cref="Exception.InnerException"/>.</param>
```
Comment (riemannulus) [inline Libplanet/Tx/InvalidTxException.cs:35]: trivial, but...
```suggestion
        /// </param> 
        /// <param name="innerException">The <see cref="Exception"/> for
        /// <see cref="Exception.InnerException"/>.</param>
```

Comment (colibrishin) [reply Libplanet/Tx/InvalidTxException.cs:35]: And like, this?

https://github.com/colibrishin/libplanet/blob/9c8fe16a2bb18b8e239130c2285c98e52e79af59/Libplanet/Tx/TxPolicyViolationException.cs#L32-L34

File: CHANGES.md [hunk 2]
```diff
@@ -73,6 +73,9 @@ Released on April 19th, 2022.
     [[#1866], [#1891]]
  -  (Libplanet.Net) `IMessageCodec.Encode()` now requires a *matching*
     `PrivateKey` to be provided for `Peer`.  [[#1904], [#1905]]
+ -  `TxPolicyViolationException` and `InvalidTxException` now have a new
+    constructor that takes an `Exception` as their `Exception.InnerException`.
+    [[#1830], [#1912], [#1916]]
```
Comment (dahlia) [inline CHANGES.md:78]: Apparently these reference links are not [defined](https://spec.commonmark.org/0.30/#link-reference-definition).  Usually we place definitions below the section:

https://github.com/colibrishin/libplanet/blame/cb6b0b3091bbbc456e5b1f9f96dea2597931fc2c/CHANGES.md#L87-L92

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 3]
```diff
@@ -2005,10 +2005,82 @@ private async Task FilterLowerNonceTxAfterStaging()
...
+            }
+            catch (TxPolicyViolationException e)
+            {
+                Assert.NotNull(e.InnerException);
+
+                // This is visual representation of the test.
+                // In actual use-case, this debugging lines do
+                // not show.
+                _logger.Debug(e.ToString());
+                _logger.Debug(e.InnerException.ToString());
```
Comment (dahlia) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2055]: The first parameter of logging methods take a template string, rather than a bare string, which means it can misbehave if its first argument contains some placeholders like `{0}`.  I know `e.ToString()` and `e.InnerException.ToString()` probably does not contains such things at the moment, someone might change these methods in the future so that their return values contain such placeholder syntax.

```suggestion
                _logger.Debug("Exception: {0}", e.ToString());
                _logger.Debug("InnerException: {0}", e.InnerException.ToString());
```

File: Libplanet/Tx/TxPolicyViolationException.cs [hunk 4]
```diff
@@ -23,5 +23,21 @@ public TxPolicyViolationException(TxId txid, string message)
             : base(txid, message)
         {
         }
+
+        /// <inheritdoc cref="Libplanet.Tx.TxPolicyViolationException" />
```
Comment (dahlia) [inline Libplanet/Tx/TxPolicyViolationException.cs:27]: What's your intention on this?  I'm curious why it inherits docs from class `TxPolicyViolationException`.

Comment (colibrishin) [reply Libplanet/Tx/TxPolicyViolationException.cs:27]: I was thinking that `TxPolicyViolationException` have same summary naively. 
Now think about this, It will be better if one can notice that also there's a constructor for innerException from summary.

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 5]
```diff
@@ -2005,10 +2005,82 @@ private async Task FilterLowerNonceTxAfterStaging()
             Assert.Equal(4, _blockChain.StagePolicy.Iterate(_blockChain, filtered: false).Count());
         }
 
+        [Fact]
+        private void CheckIfTxPolicyExceptionHasInnerException()
+        {
+            IValue value = null;
```
Comment (limebell) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2011]:
```suggestion
```
This variable is only assigned, not used in anywhere.

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 6]
```diff
@@ -2005,10 +2005,82 @@ private async Task FilterLowerNonceTxAfterStaging()
...
+            var policy = new NullPolicyButTxPolicyAlwaysThrows<DumbAction>(
+                c =>
+                {
+                    // ReSharper disable AccessToModifiedClosure
+                    // The following method calls should not throw any exceptions:
+                    c?.GetStates(new[] { default(Address) });
+                    value = c?.GetState(default);
+                    // ReSharper restore AccessToModifiedClosure
```
Comment (limebell) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2019]:
```suggestion
                    // The following method calls should not throw any exceptions:
                    c?.GetStates(new[] { default(Address) });
                    c?.GetState(default);
```

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 7]
```diff
@@ -2005,10 +2005,82 @@ private async Task FilterLowerNonceTxAfterStaging()
...
+            }
+            catch (TxPolicyViolationException e)
+            {
+                Assert.NotNull(e.InnerException);
+
+                // This is visual representation of the test.
+                // In actual use-case, this debugging lines do
+                // not show.
+                _logger.Debug("Exception: {0}", e.ToString());
+                _logger.Debug("InnerException: {0}", e.InnerException.ToString());
```
Comment (limebell) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2055]:
```suggestion
                _logger.Debug("Exception: {Exception}", e.ToString());
                _logger.Debug("InnerException: {InnerException}", e.InnerException.ToString());
```
Named properties is suggested in Serilog structured logging instead of positional ones.

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 8]
```diff
@@ -2005,10 +2005,82 @@ private async Task FilterLowerNonceTxAfterStaging()
...
+            {
+                var chain = new BlockChain<DumbAction>(
+                    policy,
+                    new VolatileStagePolicy<DumbAction>(),
+                    store,
+                    stateStore,
+                    genesisWithTx
+                );
+            }
+            catch (TxPolicyViolationException e)
```
Comment (limebell) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2047]: This `catch` block is called only when `try` block throws exception, but it's not guaranteed. How about using `Assert.Throws<T>()` to insure exception is thrown.
```csharp
Assert.Throws<TxPolicyViolationException>(() => {
    try
    {
        ....
    }
    catch (TxPolicyViolationException e)
    {
        ....

        throw;
    }
});
```

**Review by dahlia — COMMENTED** [review]
Could you squash these three commits into one?  I believe those three patches have no reason to be distinct each other:

- 7e50cf463a627c3f72adb4b9f090655df50d8643
- 3930262716e144131a05cc4fed44323cf79b192d
- 08d5dc23e3927f919f4bb10fb31dd4c524f37fad

File: Libplanet/Tx/InvalidTxException.cs [hunk 9]
```diff
@@ -16,12 +16,33 @@ public abstract class InvalidTxException : Exception
         /// the <see cref="Exception.Message"/> string.</param>
         /// <param name="message">A descriptive error message for programmers.
         /// </param>
-        protected InvalidTxException(TxId txid, string message)
+        protected InvalidTxException(
+            TxId txid,
+            string message)
```
Comment (limebell) [inline Libplanet/Tx/InvalidTxException.cs:21]: This change seems not required.

File: Libplanet/Tx/TxPolicyViolationException.cs [hunk 10]
```diff
@@ -11,7 +11,9 @@ namespace Libplanet.Tx
     public class TxPolicyViolationException : InvalidTxException
     {
         /// <summary>
-        /// Creates a new <see cref="TxPolicyViolationException"/> instance.
+        /// Creates a new <see cref="TxPolicyViolationException"/> instance. Use
+        /// <see cref="TxPolicyViolationException(TxId, string, Exception)"/> if innerException
+        /// is required.
```
Comment (limebell) [inline Libplanet/Tx/TxPolicyViolationException.cs:16]: It would be great if we add this statement to the document of `InvalidTxException` too.

**Review by limebell — COMMENTED** [review]
Great work. I've added some style-related comments. :)

File: Libplanet.Tests/Blockchain/BlockChainTest.cs (hunk 8 above)
Comment (colibrishin) [reply Libplanet.Tests/Blockchain/BlockChainTest.cs]: I should get used to lambda function, the `Action` (in C#?). 😅

**Comment by colibrishin** [comment]
Following suggestions have been applied. 🤖

**Review by dahlia — APPROVED** [review]

**Review by limebell — DISMISSED** [review]
LGTM :)

**Comment by dahlia** [comment]
@riemannulus Do you have anything you want @colibrishin to change more?

File: Libplanet.Tests/Blockchain/BlockChainTest.cs [hunk 11]
```diff
@@ -2005,10 +2005,85 @@ private async Task FilterLowerNonceTxAfterStaging()
...
+        {
+            var policy = new NullPolicyButTxPolicyAlwaysThrows<DumbAction>(
+                c =>
+                {
+                    // ReSharper disable AccessToModifiedClosure
+                    // The following method calls should not throw any exceptions:
+                    c?.GetStates(new[] { default(Address) });
+                    c?.GetState(default);
+                    // ReSharper restore AccessToModifiedClosure
+                });
```
Comment (riemannulus) [inline Libplanet.Tests/Blockchain/BlockChainTest.cs:2019]: It's trivial but we use the variable `x` in situation like this.

**Review by limebell — APPROVED** [review]

**Review by dahlia — APPROVED** [review]

**Review by riemannulus — APPROVED** [review]
+1
