### PR TITLE
Access blocks and transactions of the chain with lock

### LINKED ISSUE #409: Bencodex.DecodingException: stream terminates unexpectedly at 0
```
08/07/2019 05:55:56 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
?Zw????)t???,:55:56 +00:00: The raw message[NetMQMessage[       ?s?
08/07/2019 05:55:56 +00:00: Something went wrong during message parsing: "Bencodex.DecodingException: stream terminates unexpectedly at 0
  at Bencodex.Codec.Decode (Bencodex.Misc.ByteChunkQueue buffer, System.IO.Stream input) [0x000c7] in <462f452b9f3d4750849a760da428a301>:0
  at Bencodex.Codec.Decode (System.IO.Stream input) [0x00025] in <462f452b9f3d4750849a760da428a301>:0
  at Libplanet.Serialization.BencodexFormatter`1[T].Deserialize (System.IO.Stream serializationStream) [0x00000] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Tx.Transaction`1[T].FromBencodex (System.Byte[] bytes) [0x0000d] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Store.LiteDBStore.GetTransaction[T] (Libplanet.Tx.TxId txid) [0x0005b] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Store.TransactionSet`1[T].ContainsKey (Libplanet.Tx.TxId key) [0x00006] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Net.Swarm`1+<>c__DisplayClass98_0[T].<ProcessTxIds>b__0 (Libplanet.Tx.TxId id) [0x00010] in <e16ca518ab934a82bde650ed7164c828>:0
  at System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () [0x00037] in <3e4da02cf86b4fc686ed0ac61bffc210>:0
  at System.Collections.Immutable.DisposableEnumeratorAdapter`2[T,TEnumerator].MoveNext () [0x0001a] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] other, System.Collections.Immutable.ImmutableHashSet`1+MutationInput[T] origin) [0x00077] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] items, System.Boolean avoidWithComparer) [0x00034] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] other) [0x0000b] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Collections.Generic.IEqualityComparer`1[T] equalityComparer) [0x0001d] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <6518d0e60ca84f6b915c07341a031a32>:0
  at Libplanet.Net.Swarm`1+<ProcessTxIds>d__98[T].MoveNext () [0x00052] in <e16ca518ab934a82bde650ed7164c828>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at Libplanet.Net.Swarm`1+<ProcessMessageAsync>d__92[T].MoveNext () [0x0026f] in <e16ca518ab934a82bde650ed7164c828>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at Libplanet.Net.Swarm`1+<>c__DisplayClass112_0+<<ReceiveMessage>b__0>d[T].MoveNext () [0x0007b] in <e16ca518ab934a82bde650ed7164c828>:0 "

08/07/2019 05:55:56 +00:00: Trying to fetch txs...
08/07/2019 05:55:56 +00:00: Receiving tx...
08/07/2019 05:55:56 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:56 +00:00: Trying to fetch txs...
08/07/2019 05:55:56 +00:00: The raw message[NetMQMessage[?w?2w]?a???T??%???,
08/07/2019 05:55:56 +00:00: Receiving tx...
08/07/2019 05:55:56 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:56 +00:00: Trying to fetch txs...
08/07/2019 05:55:56 +00:00: The raw message[NetMQMessage[?9!&??X, ??????r?y,
08/07/2019 05:55:56 +00:00: Txs staged successfully.
08/07/2019 05:55:57 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:57 +00:00: Trying to fetch txs...
08/07/2019 05:55:57 +00:00: The raw message[NetMQMessage[BC??G??gj????l???,
08/07/2019 05:55:57 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:57 +00:00: Trying to fetch txs...
08/07/2019 05:55:57 +00:00: Required tx count: 1.
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: The raw message[NetMQMessage[?
                                                          ~?\????R??wE7?HR,
08/07/2019 05:55:57 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:57 +00:00: Trying to fetch txs...
08/07/2019 05:55:57 +00:00: TxIds was sent from unknown peer. ignored.
08/07/2019 05:55:57 +00:00: Txs staged successfully.
08/07/2019 05:55:57 +00:00: Trying to distribute own delta (+0, -0)...
08/07/2019 05:55:57 +00:00: Required tx count: 2.
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: Required tx count: 2.
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: The data file for the transaction "f1b06b7b5b3007bec91b12f0756b015c6c06562934eddbbb580f681daebb51eb" seems corrupted; it will be treated nonexistent and removed at all.
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: Something went wrong during message parsing: "Bencodex.DecodingException: stream terminates unexpectedly at 0
  at Bencodex.Codec.Decode (Bencodex.Misc.ByteChunkQueue buffer, System.IO.Stream input) [0x000c7] in <462f452b9f3d4750849a760da428a301>:0
  at Bencodex.Codec.Decode (System.IO.Stream input) [0x00025] in <462f452b9f3d4750849a760da428a301>:0
  at Libplanet.Serialization.BencodexFormatter`1[T].Deserialize (System.IO.Stream serializationStream) [0x00000] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Tx.Transaction`1[T].FromBencodex (System.Byte[] bytes) [0x0000d] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Store.LiteDBStore.GetTransaction[T] (Libplanet.Tx.TxId txid) [0x0005b] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Store.TransactionSet`1[T].ContainsKey (Libplanet.Tx.TxId key) [0x00006] in <e16ca518ab934a82bde650ed7164c828>:0
  at Libplanet.Net.Swarm`1+<>c__DisplayClass98_0[T].<ProcessTxIds>b__0 (Libplanet.Tx.TxId id) [0x00010] in <e16ca518ab934a82bde650ed7164c828>:0
  at System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () [0x00037] in <3e4da02cf86b4fc686ed0ac61bffc210>:0
  at System.Collections.Immutable.DisposableEnumeratorAdapter`2[T,TEnumerator].MoveNext () [0x0001a] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] other, System.Collections.Immutable.ImmutableHashSet`1+MutationInput[T] origin) [0x00077] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] items, System.Boolean avoidWithComparer) [0x00034] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet`1[T].Union (System.Collections.Generic.IEnumerable`1[T] other) [0x0000b] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Collections.Generic.IEqualityComparer`1[T] equalityComparer) [0x0001d] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <6518d0e60ca84f6b915c07341a031a32>:0
  at Libplanet.Net.Swarm`1+<ProcessTxIds>d__98[T].MoveNext () [0x00052] in <e16ca518ab934a82bde650ed7164c828>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at Libplanet.Net.Swarm`1+<ProcessMessageAsync>d__92[T].MoveNext () [0x0026f] in <e16ca518ab934a82bde650ed7164c828>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0
  at Libplanet.Net.Swarm`1+<>c__DisplayClass112_0+<<ReceiveMessage>b__0>d[T].MoveNext () [0x0007b] in <e16ca518ab934a82bde650ed7164c828>:0 "
08/07/2019 05:55:57 +00:00: Required tx count: 3.
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:57 +00:00: The raw message[NetMQMessage[?9!&??X, ??????r?y,
08/07/2019 05:55:57 +00:00: The message[Libplanet.Net.Messages.TxIds] has parsed.
08/07/2019 05:55:57 +00:00: Trying to fetch txs...
08/07/2019 05:55:57 +00:00: Receiving tx...
08/07/2019 05:55:58 +00:00: The data file for the transaction "cf5d307b095c5d5b233378a62fb6939e67dcc57601ee2ad227d2256032121334" seems corrupted; it will be treated nonexistent and removed at all.
08/07/2019 05:55:58 +00:00: Receiving tx...
```
```

### PR DESCRIPTION
**Pull request by earlbread**
#409 occurs when a task tries to read a block or transaction from `BlockChain<T>.Blocks` or `BlockChain<T>.Transactions` while another task is writing it. This fixes #409 by changing blocks and transactions in the `BlockChain<T>` so that it cannot be accessed without the lock from the outside of the chain.

### CODE REVIEW

File: Libplanet/Blockchain/BlockChain.cs [hunk 1]
```diff
@@ -149,6 +169,98 @@ public Block<T> Tip
...
+        }
+
+        /// <summary>
+        /// Gets the transaction corresponding to the <paramref name="txId"/>.
+        /// </summary>
+        /// <param name="txId">A <see cref="TxId"/> of the <see cref="Transaction{T}"/> to get.
+        /// </param>
+        /// <exception cref="KeyNotFoundException">Thrown when there is no
+        /// <see cref="Transaction{T}"/> with a given <paramref name="txId"/>.</exception>
+        public Transaction<T> this[TxId txId]
```
Comment (dahlia) [inline Libplanet/Blockchain/BlockChain.cs]: Instead of overloading this and making indexer able to return two distinct types, how about declare a method like `GetTransaction(TxId)`?

Comment (earlbread) [reply Libplanet/Blockchain/BlockChain.cs]: That would be better. Fixed.

**Comment by longfin** [comment]
I think that we also need to add a mutex for block synchronization to `LiteDBStore`. (even in other PR)

File: Libplanet/Blockchain/BlockChain.cs [hunk 2]
```diff
@@ -123,24 +133,57 @@ public Block<T> Tip
...
+                {
+                    _rwlock.ExitReadLock();
+                }
+            }
+        }
+
+        /// <summary>
+        /// Gets the block corresponding to the <paramref name="hash"/>.
+        /// </summary>
+        /// <param name="hash">A <see cref="HashDigest{T}"/> of the <see cref="Block{T}"/> to get.
```
Comment (dahlia) [inline Libplanet/Blockchain/BlockChain.cs]:
```suggestion
        /// <param name="hash">A <see cref="Block{T}.Hash"/> of the <see cref="Block{T}"/> to get.
```
